<a href="https://colab.research.google.com/github/Ararine/pythondemo/blob/main/python_22_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

### 버전 확인

In [ ]:
# python
import sys
print(sys.version)
print('='*30)
!python --version

3.8.16 (default, Dec  7 2022, 01:12:13) 
[GCC 7.5.0]
Python 3.8.16


In [ ]:
# numpy
np.__version__

'1.21.6'

In [ ]:
# pandas
pd.__version__

'1.3.5'

In [ ]:
!pip freeze

- numpy datatype : ndarray, matrix
- pandas datatype : Series(벡터), DataFrame(행렬)

### 구글 드라이브 연동

In [2]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/python_demo

Mounted at /content/drive
/content/drive/MyDrive/python_demo


### 파일 형식 데이터 불러오기

In [ ]:
# 읽어오는 파일에 컬럼명이 없으면 header = None을 설정한다.
# 그렇지 않으면 첫번째 줄을 컬럼명으로 인식을 하기 때문이다.
# header 파라미터의 default:'infer' 이다.
data = pd.read_csv('pdsample/num.txt', header = None)
data

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [ ]:
type(data)

pandas.core.frame.DataFrame

In [ ]:
# 컬럼(열)
print(data[0])
print(type(data[0]))

0    1
1    6
Name: 0, dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
# index(행)
print(data.iloc[0])
print(type(data.iloc[0])) # Series

0    1
1    2
2    3
3    4
4    5
Name: 0, dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
# numpy 참고
a = np.arange(12).reshape(3,4)
print(a)
print(a[1][2]) # [행][열]을 의미
print(a[1]) # 행을 의미
print(a[1,2:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[4 5 6 7]
[6 7]


In [ ]:
# python list 참고
b = [[ 0,  1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11]]
print(b[1][2])
print(b[1])
# print(b[1,2:]) # list에서는 슬라이싱 안됨

6
[4, 5, 6, 7]


In [ ]:
# .values하면 numpy 포맷으로 변환한다.
# 내부적으로 numpy로 되어 있기 때문에 가능하다.
print(data.values)
print(type(data.values)) # numpy.ndarray
data.values # jupitor 에서는 데이터 타입도 제공

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
# __array__가 있으면 numpy와 호환된다.
dir(data)

### 웹 주소에서 데이터 불러오기

In [3]:
# header은 기본이 첫줄이 컬럼명으로 가져오도록 설정이 되어 있기 때문에 header='infer' 생략 가능하다.
data = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv', header = 'infer')
data

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
# 전반적인 데이터 정보 확인
data.info() # RangeIndex : 데이터 수

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [ ]:
# 기본적으로 앞의 5개를 보여줌
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
# 기본적으로 끝의 5개를 보여줌
data.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
# random으로 1개씩 보여줌
data.sample()

total_bill  tip   sex smoker  day    time  size
98       21.01  3.0  Male    Yes  Fri  Dinner     2

In [ ]:
# 보여줄 개수를 지정할 수 있음
data.head(10)
data.tail(10)
data.sample(10)

total_bill   tip     sex smoker   day    time  size
162       16.21  2.00  Female     No   Sun  Dinner     3
73        25.28  5.00  Female    Yes   Sat  Dinner     2
90        28.97  3.00    Male    Yes   Fri  Dinner     2
63        18.29  3.76    Male    Yes   Sat  Dinner     4
9         14.78  3.23    Male     No   Sun  Dinner     2
106       20.49  4.06    Male    Yes   Sat  Dinner     2
68        20.23  2.01    Male     No   Sat  Dinner     2
100       11.35  2.50  Female    Yes   Fri  Dinner     2
129       22.82  2.18    Male     No  Thur   Lunch     3
56        38.01  3.00    Male    Yes   Sat  Dinner     4

In [ ]:
# 데이터만 가져옴
data.values

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]], dtype=object)

In [ ]:
data.index # 행

RangeIndex(start=0, stop=244, step=1)

In [ ]:
data.columns # 열

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
# dict 타입
dictdata = {'name':'홍길동', 'age':'30'}
# dictdata.name
dictdata['name']

'홍길동'

In [ ]:
dir(dict)
dict.items

<method 'items' of 'dict' objects>

In [ ]:
# pandas는 dictionary와 attribute 방식 모두 가져올 수 있다.
# dictionary 방식 이용
data['tip']
data['tip'][2]

3.5

In [ ]:
# attribute 방식 이용
data.tip

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [ ]:
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
#data['tip', 'day']
# 컬럼을 fancying indexing을 이용해서 가져올 때 index을 이용해서 가져올 수 있다.
#data[[0,2]]
data[['tip', 'day']]

tip   day
0    1.01   Sun
1    1.66   Sun
2    3.50   Sun
3    3.31   Sun
4    3.61   Sun
..    ...   ...
239  5.92   Sat
240  2.00   Sat
241  2.00   Sat
242  1.75   Sat
243  3.00  Thur

[244 rows x 2 columns]

In [ ]:
# TypeError발생
# 컬럼을 slicing을 이용해서 가져올 수 없다.
#data['tip':'day']

# row를 slicing을 이용해서 가져올 때는 index을 이용해서 가져온다.
data[1:3]

total_bill   tip   sex smoker  day    time  size
1       10.34  1.66  Male     No  Sun  Dinner     3
2       21.01  3.50  Male     No  Sun  Dinner     3

In [ ]:
# KeyError
#data[3]
data.iloc[3] # indexing

total_bill     23.68
tip             3.31
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 3, dtype: object

- 하나의 컬럼 또는 행 가져오는 Series로 리턴한다.
- fancy indexing을 이용해서 하나의 컬럼 또는 행을 가져오면 DataFrame으로 리턴한다.

In [ ]:
type(data.iloc[3])

pandas.core.series.Series

In [ ]:
type(data['tip']) #Series
# type(data.tip) #series

pandas.core.series.Series

In [ ]:
type(data[['tip']]) # DataFrame

pandas.core.frame.DataFrame

In [ ]:
data.iloc[0:5]
data.iloc[0:5, :]

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
data.iloc[[0,3,5]] # fancy indexing, 행의 경우 data[['tip', 'smoker', 'day']]

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
3       23.68  3.31    Male     No  Sun  Dinner     2
5       25.29  4.71    Male     No  Sun  Dinner     4

In [ ]:
# 3행 1열
data.iloc[3][1] # list : a[3][1] # array : a[3,1]

3.31

In [ ]:
data.iloc[0:3, 1:4]

tip     sex smoker
0  1.01  Female     No
1  1.66    Male     No
2  3.50    Male     No

In [ ]:
data.iloc[[0,3,5],[1,4,5]]

tip  day    time
0  1.01  Sun  Dinner
3  3.31  Sun  Dinner
5  4.71  Sun  Dinner

- iloc는 indexer을 이용해서 가져오고, loc는 이름을 이용해서 가져온다.

In [ ]:
# 행은 이름이 설정되어 있지 않아 자동으로 생성된 Range Index가 이름이 된다.
data.loc[0, 'tip'] # 행은 인덱스를 이용해서 가져오고, 열은 컬럼명으로 가져온다.

1.01

In [ ]:
data.loc[0:5, 'tip':'time']

tip     sex smoker  day    time
0  1.01  Female     No  Sun  Dinner
1  1.66    Male     No  Sun  Dinner
2  3.50    Male     No  Sun  Dinner
3  3.31    Male     No  Sun  Dinner
4  3.61  Female     No  Sun  Dinner
5  4.71    Male     No  Sun  Dinner

In [ ]:
data.loc[[0,3,5],['tip','day','time']]

tip  day    time
0  1.01  Sun  Dinner
3  3.31  Sun  Dinner
5  4.71  Sun  Dinner

### at
- 이름으로 한 위치의 값만 가져온다.

In [ ]:
data.at[0, 'tip']
# data.loc[0, 'tip']
# data.iloc[0, 1]

1.01

In [ ]:
# at은 slicing을 사용할 수 없다.
#data.at[0:3, 'tip']

In [ ]:
# at은 fancying indexing을 사용할 수 없다.
#data.at[[1,3,5], ['tip']]

### iat
- iat은 인덱스 번호로 한 위치의 값을 가져온다.

In [ ]:
data.iat[0,1]
#data.at[0,'tip']

1.01

In [ ]:
# iat은 슬라이싱을 사용할 수 없다.
# data.iat[0:3, 1]

### boolean indexing

In [ ]:
# data.tip >= 5
data['tip'] >= 5

0      False
1      False
2      False
3      False
4      False
       ...  
239     True
240    False
241    False
242    False
243    False
Name: tip, Length: 244, dtype: bool

In [ ]:
data[data['tip'] >= 5] # data[True, False, True, False, ...]

total_bill    tip     sex smoker   day    time  size
11        35.26   5.00  Female     No   Sun  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
39        31.27   5.00    Male     No   Sat  Dinner     3
44        30.40   5.60    Male     No   Sun  Dinner     4
46        22.23   5.00    Male     No   Sun  Dinner     2
47        32.40   6.00    Male     No   Sun  Dinner     4
52        34.81   5.20  Female     No   Sun  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
73        25.28   5.00  Female    Yes   Sat  Dinner     2
83        32.68   5.00    Male    Yes  Thur   Lunch     2
85        34.83   5.17  Female     No  Thur   Lunch     4
88        24.71   5.85    Male     No  Thur   Lunch     2
116       29.93   5.07    Male     No   Sun  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
142       41.19   5.00    Male     No  Thur   Lunch     5
143       27.05   5.00  Female     No  Thur   Lunch     6
155       29.85   5.14  Female     No   Sun  Dinner     5
156       48.17   5.00    Male     No   Sun  Dinner     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
172        7.25   5.15    Male    Yes   Sun  Dinner     2
181       23.33   5.65    Male    Yes   Sun  Dinner     2
183       23.17   6.50    Male    Yes   Sun  Dinner     4
185       20.69   5.00    Male     No   Sun  Dinner     5
197       43.11   5.00  Female    Yes  Thur   Lunch     4
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3

In [ ]:
#data.tip
#data['tip']
#a = data[data['tip'] >= 5]
#a['tip']

# 1번째의 결과는 DataFrame, 2번째의 결과는 Series
data[data['tip'] >= 5]['tip']
#data['tip'][3]

11      5.00
23      7.58
39      5.00
44      5.60
46      5.00
47      6.00
52      5.20
59      6.73
73      5.00
83      5.00
85      5.17
88      5.85
116     5.07
141     6.70
142     5.00
143     5.00
155     5.14
156     5.00
170    10.00
172     5.15
181     5.65
183     6.50
185     5.00
197     5.00
211     5.16
212     9.00
214     6.50
239     5.92
Name: tip, dtype: float64

In [ ]:
data[data['tip']>=5].loc[:,'tip':'day']

tip     sex smoker   day
11    5.00  Female     No   Sun
23    7.58    Male     No   Sat
39    5.00    Male     No   Sat
44    5.60    Male     No   Sun
46    5.00    Male     No   Sun
47    6.00    Male     No   Sun
52    5.20  Female     No   Sun
59    6.73    Male     No   Sat
73    5.00  Female    Yes   Sat
83    5.00    Male    Yes  Thur
85    5.17  Female     No  Thur
88    5.85    Male     No  Thur
116   5.07    Male     No   Sun
141   6.70    Male     No  Thur
142   5.00    Male     No  Thur
143   5.00  Female     No  Thur
155   5.14  Female     No   Sun
156   5.00    Male     No   Sun
170  10.00    Male    Yes   Sat
172   5.15    Male    Yes   Sun
181   5.65    Male    Yes   Sun
183   6.50    Male    Yes   Sun
185   5.00    Male     No   Sun
197   5.00  Female    Yes  Thur
211   5.16    Male    Yes   Sat
212   9.00    Male     No   Sat
214   6.50  Female    Yes   Sat
239   5.92    Male     No   Sat

In [ ]:
data[data['tip']>=5].iloc[:,1:5]

tip     sex smoker   day
11    5.00  Female     No   Sun
23    7.58    Male     No   Sat
39    5.00    Male     No   Sat
44    5.60    Male     No   Sun
46    5.00    Male     No   Sun
47    6.00    Male     No   Sun
52    5.20  Female     No   Sun
59    6.73    Male     No   Sat
73    5.00  Female    Yes   Sat
83    5.00    Male    Yes  Thur
85    5.17  Female     No  Thur
88    5.85    Male     No  Thur
116   5.07    Male     No   Sun
141   6.70    Male     No  Thur
142   5.00    Male     No  Thur
143   5.00  Female     No  Thur
155   5.14  Female     No   Sun
156   5.00    Male     No   Sun
170  10.00    Male    Yes   Sat
172   5.15    Male    Yes   Sun
181   5.65    Male    Yes   Sun
183   6.50    Male    Yes   Sun
185   5.00    Male     No   Sun
197   5.00  Female    Yes  Thur
211   5.16    Male    Yes   Sat
212   9.00    Male     No   Sat
214   6.50  Female    Yes   Sat
239   5.92    Male     No   Sat

In [ ]:
data[data['tip']>=5][['tip','day']]

tip   day
11    5.00   Sun
23    7.58   Sat
39    5.00   Sat
44    5.60   Sun
46    5.00   Sun
47    6.00   Sun
52    5.20   Sun
59    6.73   Sat
73    5.00   Sat
83    5.00  Thur
85    5.17  Thur
88    5.85  Thur
116   5.07   Sun
141   6.70  Thur
142   5.00  Thur
143   5.00  Thur
155   5.14   Sun
156   5.00   Sun
170  10.00   Sat
172   5.15   Sun
181   5.65   Sun
183   6.50   Sun
185   5.00   Sun
197   5.00  Thur
211   5.16   Sat
212   9.00   Sat
214   6.50   Sat
239   5.92   Sat

#### 요일이 'Sun'이거나 'Sat'의 tip과 day의 값을 가져오기


In [ ]:
# print(data[data['day'] == 'Sun'][['tip','day']])
# print(data[data['day'] == 'Sat'][['tip','day']])
#dir(type(data[data['day']== 'Sat']))
# a = data[data['day'] == 'Sun']
# b = data[data['day'] == 'Sat']
# a.append(b)[['tip','day']]
data[(data['day'] == 'Sun') | (data['day'] == 'Sat')][['tip','day']]
a = data[(data['day'] == 'Sun') | (data['day'] == 'Sat')]
a['day'].unique() # 해당되는 값을 확인할 수 있다.
a[['tip','day']]

tip  day
0    1.01  Sun
1    1.66  Sun
2    3.50  Sun
3    3.31  Sun
4    3.61  Sun
..    ...  ...
238  4.67  Sat
239  5.92  Sat
240  2.00  Sat
241  2.00  Sat
242  1.75  Sat

[163 rows x 2 columns]

In [ ]:
print(len([1,2,3]))
print(len('123'))
print(len({'a':1, 'b':2, 'c':3}))
print(len(data))

# [1,2,3].size # AttributeError
#'123'.size.size # AttributeError
#{'a':1, 'b':2, 'c':3}.size # AttributeError
import numpy as np
print((np.array([1,2,3])).size)
print(data.size) # 244 * 7 : 행 * 열
data['tip'].size

data.tip


3
3
3
244
3
1708


0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [4]:
# 컬럼명을 바꿀 때 mapper, columns 옵션을 이용해서 변경할 수 있다.
data2 = data.rename(mapper={'size':'size_'}, axis=1)
data2 = data.rename(columns = {'size' : 'size_'})
data2

total_bill   tip     sex smoker   day    time  size_
0         16.99  1.01  Female     No   Sun  Dinner      2
1         10.34  1.66    Male     No   Sun  Dinner      3
2         21.01  3.50    Male     No   Sun  Dinner      3
3         23.68  3.31    Male     No   Sun  Dinner      2
4         24.59  3.61  Female     No   Sun  Dinner      4
..          ...   ...     ...    ...   ...     ...    ...
239       29.03  5.92    Male     No   Sat  Dinner      3
240       27.18  2.00  Female    Yes   Sat  Dinner      2
241       22.67  2.00    Male    Yes   Sat  Dinner      2
242       17.82  1.75    Male     No   Sat  Dinner      2
243       18.78  3.00  Female     No  Thur  Dinner      2

[244 rows x 7 columns]

### category
- category는 문자열(object)보다 더 많은 기능을 할 수 있다.
- category는 문자 또는 숫자도 가능하다.
- category는 몇 개로 분류할 수 있을 때 사용한다. ex)성별(남,여)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [7]:
type(data['sex'])

pandas.core.series.Series

In [9]:
print(data['sex'].dtype)

object


In [11]:
data['sex']

0      Female
1        Male
2        Male
3        Male
4      Female
        ...  
239      Male
240    Female
241      Male
242      Male
243    Female
Name: sex, Length: 244, dtype: object

In [12]:
# object을 category로 데이터 타입로 변경한다.
data['sex'] = data['sex'].astype('category') # astype : 타입을 변경시키준다. 원본이 변하지 않기에 다시 저장을 해준다.

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    object  
 4   day         244 non-null    object  
 5   time        244 non-null    object  
 6   size        244 non-null    int64   
dtypes: category(1), float64(2), int64(1), object(3)
memory usage: 11.9+ KB


In [15]:
data.sample()

total_bill  tip   sex smoker   day   time  size
142       41.19  5.0  Male     No  Thur  Lunch     5

In [20]:
# data에서 Female만 가져오기
# data[data['sex'] == 'Female']
data[data.sex == 'Female']

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
..          ...   ...     ...    ...   ...     ...   ...
226       10.09  2.00  Female    Yes   Fri   Lunch     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[87 rows x 7 columns]

In [23]:
# data[data['sex'] == 'Female']['sex'].unique()
data[data.sex == 'Female']['sex'].unique()

['Female']
Categories (2, object): ['Female', 'Male']

#### 금요일에 온 여자만 가져오기


In [30]:
# dictionary 방식
data['day'].unique()
data[(data['day']=='Fri') & (data['sex']=='Female')]

total_bill   tip     sex smoker  day    time  size
92         5.75  1.00  Female    Yes  Fri  Dinner     2
93        16.32  4.30  Female    Yes  Fri  Dinner     2
94        22.75  3.25  Female     No  Fri  Dinner     2
100       11.35  2.50  Female    Yes  Fri  Dinner     2
101       15.38  3.00  Female    Yes  Fri  Dinner     2
221       13.42  3.48  Female    Yes  Fri   Lunch     2
223       15.98  3.00  Female     No  Fri   Lunch     3
225       16.27  2.50  Female    Yes  Fri   Lunch     2
226       10.09  2.00  Female    Yes  Fri   Lunch     2

In [31]:
# attribute 방식
data[(data.day == 'Fri') & (data.sex == 'Female')]

total_bill   tip     sex smoker  day    time  size
92         5.75  1.00  Female    Yes  Fri  Dinner     2
93        16.32  4.30  Female    Yes  Fri  Dinner     2
94        22.75  3.25  Female     No  Fri  Dinner     2
100       11.35  2.50  Female    Yes  Fri  Dinner     2
101       15.38  3.00  Female    Yes  Fri  Dinner     2
221       13.42  3.48  Female    Yes  Fri   Lunch     2
223       15.98  3.00  Female     No  Fri   Lunch     3
225       16.27  2.50  Female    Yes  Fri   Lunch     2
226       10.09  2.00  Female    Yes  Fri   Lunch     2

In [35]:
data[(data['day']=='Fri') & (data['sex']=='Female')]['sex'].unique()
data[(data.day=='Fri') & (data['sex']=='Female')]['day'].unique()

array(['Fri'], dtype=object)

### describe
- describe는 기초적인 통계 분석을 해준다.

In [36]:
# describe()의 기본은 데이터가 숫자로 된 컬럼만 가져온다.
data.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [38]:
type(data.describe())

pandas.core.frame.DataFrame

In [40]:
# pandas는 numpy기반이라서 numpy 기능을 사용할 수 있다.
data.describe().T

count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

In [45]:
# describe()은 기본적으로 숫자형 데이터만 분석한다.
# include() 옵션을 사용하면 다른 분석할 데이터 타입을 지정할 수 있다.
data.describe(include=['object']) # object만 출력
data.describe(include=['float64', 'object']) # 숫자와 object 모두 출력

total_bill         tip smoker  day    time
count   244.000000  244.000000    244  244     244
unique         NaN         NaN      2    4       2
top            NaN         NaN     No  Sat  Dinner
freq           NaN         NaN    151   87     176
mean     19.785943    2.998279    NaN  NaN     NaN
std       8.902412    1.383638    NaN  NaN     NaN
min       3.070000    1.000000    NaN  NaN     NaN
25%      13.347500    2.000000    NaN  NaN     NaN
50%      17.795000    2.900000    NaN  NaN     NaN
75%      24.127500    3.562500    NaN  NaN     NaN
max      50.810000   10.000000    NaN  NaN     NaN

In [49]:
# 데이터 타입이 object일 때만 가져온다.
#data.describe(include=['object'])
data.describe(include='O') # 대문자 알파벳 O, object와 같은 결과

smoker  day    time
count     244  244     244
unique      2    4       2
top        No  Sat  Dinner
freq      151   87     176

In [51]:
np.number

numpy.number

In [55]:
data.describe(include=['float64'])
data.describe(include=np.number) # 

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [58]:
# 모든 타입의 데이터를 분석할 때는 include='all'로 설정한다.
data.describe(include='all')

total_bill         tip   sex smoker  day    time        size
count   244.000000  244.000000   244    244  244     244  244.000000
unique         NaN         NaN     2      2    4       2         NaN
top            NaN         NaN  Male     No  Sat  Dinner         NaN
freq           NaN         NaN   157    151   87     176         NaN
mean     19.785943    2.998279   NaN    NaN  NaN     NaN    2.569672
std       8.902412    1.383638   NaN    NaN  NaN     NaN    0.951100
min       3.070000    1.000000   NaN    NaN  NaN     NaN    1.000000
25%      13.347500    2.000000   NaN    NaN  NaN     NaN    2.000000
50%      17.795000    2.900000   NaN    NaN  NaN     NaN    2.000000
75%      24.127500    3.562500   NaN    NaN  NaN     NaN    3.000000
max      50.810000   10.000000   NaN    NaN  NaN     NaN    6.000000

In [61]:
# day 컬럼의 요소개수 244개
data['day'].values.size

244

In [63]:
# value_counts()는 unique한 값과 그 개수를 알려준다(Series만 사용한다.)
data['day'].value_counts()

Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64

In [65]:
data['sex'].value_counts()

Male      157
Female     87
Name: sex, dtype: int64

In [67]:
data['size'].value_counts()

2    156
3     38
4     37
5      5
1      4
6      4
Name: size, dtype: int64

In [71]:
# 주말고객수와 평일 고객수를 구하기
a = (data['day']=='Sat') | (data['day'] == 'Sun')
a.value_counts() # True : 주말, False : 평일

True     163
False     81
Name: day, dtype: int64

In [73]:
#1 in [1,2,3,4]
5 in [1,2,3,4]

False

In [76]:
# 같은 컬럼에 있는 값을 가지고 검색할 때 isin()을 사용할 수 있다.
b = data['day'].isin({'Sun', 'Sat'})
b.value_counts()

True     163
False     81
Name: day, dtype: int64

In [78]:
b.unique()

array([ True, False])

In [79]:
### where

In [86]:
a = np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [89]:
# where의 인자는 조건이다.
# 조건만 넣을 경우 True의 위치를 리턴한다.
np.where(a>30) # 출력되는 값은 index이다

(array([3, 4]),)

In [90]:
# where는 인자 개수에 따라서 기능이 달라진다.
# 조건이 True이면 0, False이면 100을 반환한다.
np.where(a>30, 0, 100) # (조건, True, False)

array([100, 100, 100,   0,   0])

- describe 결과를 pandas에서 제공하는 함수


In [91]:
data.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [92]:
data['tip'].count()

244

In [93]:
data['tip'].mean()

2.99827868852459

In [94]:
data['tip'].max()

10.0

In [95]:
data['tip'].min()

1.0

In [96]:
data['tip'].std()

1.3836381890011822

- describe()결과를 numpy에서 제공하는 함

In [104]:
import numpy.ma as ma

In [99]:
# tips 데이터셋에서 tip만 가져옴
kk = data.values[:,1].copy()
kk

array([1.01, 1.66, 3.5, 3.31, 3.61, 4.71, 2.0, 3.12, 1.96, 3.23, 1.71,
       5.0, 1.57, 3.0, 3.02, 3.92, 1.67, 3.71, 3.5, 3.35, 4.08, 2.75,
       2.23, 7.58, 3.18, 2.34, 2.0, 2.0, 4.3, 3.0, 1.45, 2.5, 3.0, 2.45,
       3.27, 3.6, 2.0, 3.07, 2.31, 5.0, 2.24, 2.54, 3.06, 1.32, 5.6, 3.0,
       5.0, 6.0, 2.05, 3.0, 2.5, 2.6, 5.2, 1.56, 4.34, 3.51, 3.0, 1.5,
       1.76, 6.73, 3.21, 2.0, 1.98, 3.76, 2.64, 3.15, 2.47, 1.0, 2.01,
       2.09, 1.97, 3.0, 3.14, 5.0, 2.2, 1.25, 3.08, 4.0, 3.0, 2.71, 3.0,
       3.4, 1.83, 5.0, 2.03, 5.17, 2.0, 4.0, 5.85, 3.0, 3.0, 3.5, 1.0,
       4.3, 3.25, 4.73, 4.0, 1.5, 3.0, 1.5, 2.5, 3.0, 2.5, 3.48, 4.08,
       1.64, 4.06, 4.29, 3.76, 4.0, 3.0, 1.0, 4.0, 2.55, 4.0, 3.5, 5.07,
       1.5, 1.8, 2.92, 2.31, 1.68, 2.5, 2.0, 2.52, 4.2, 1.48, 2.0, 2.0,
       2.18, 1.5, 2.83, 1.5, 2.0, 3.25, 1.25, 2.0, 2.0, 2.0, 2.75, 3.5,
       6.7, 5.0, 5.0, 2.3, 1.5, 1.36, 1.63, 1.73, 2.0, 2.5, 2.0, 2.74,
       2.0, 2.0, 5.14, 5.0, 3.75, 2.61, 2.0, 3.5, 2.5, 2.0, 2.0, 3.

In [105]:
# tips 데이터셋에서 tip만 가져옴
xx = ma.array(data.values[:, 1])
xx

masked_array(data=[1.01, 1.66, 3.5, 3.31, 3.61, 4.71, 2.0, 3.12, 1.96,
                   3.23, 1.71, 5.0, 1.57, 3.0, 3.02, 3.92, 1.67, 3.71,
                   3.5, 3.35, 4.08, 2.75, 2.23, 7.58, 3.18, 2.34, 2.0,
                   2.0, 4.3, 3.0, 1.45, 2.5, 3.0, 2.45, 3.27, 3.6, 2.0,
                   3.07, 2.31, 5.0, 2.24, 2.54, 3.06, 1.32, 5.6, 3.0, 5.0,
                   6.0, 2.05, 3.0, 2.5, 2.6, 5.2, 1.56, 4.34, 3.51, 3.0,
                   1.5, 1.76, 6.73, 3.21, 2.0, 1.98, 3.76, 2.64, 3.15,
                   2.47, 1.0, 2.01, 2.09, 1.97, 3.0, 3.14, 5.0, 2.2, 1.25,
                   3.08, 4.0, 3.0, 2.71, 3.0, 3.4, 1.83, 5.0, 2.03, 5.17,
                   2.0, 4.0, 5.85, 3.0, 3.0, 3.5, 1.0, 4.3, 3.25, 4.73,
                   4.0, 1.5, 3.0, 1.5, 2.5, 3.0, 2.5, 3.48, 4.08, 1.64,
                   4.06, 4.29, 3.76, 4.0, 3.0, 1.0, 4.0, 2.55, 4.0, 3.5,
                   5.07, 1.5, 1.8, 2.92, 2.31, 1.68, 2.5, 2.0, 2.52, 4.2,
                   1.48, 2.0, 2.0, 2.18, 1.5, 2.83, 1.5,

In [107]:
ma.count(xx)

244

In [108]:
ma.mean(xx)

2.9982786885245902

In [110]:
ma.std(xx)

1.3807999538298958

In [119]:
# AttributeError
#ma.max(xx)
#xx.max()
type(xx) # numpy.ma.core.MaskedArray
type(kk) # numpy.ndarray
kk.max()

10.0

In [122]:
# AttributeError
#xx.min()
kk.min()

1.0

- [matplotlib](https://matplotlib.org/)


In [ ]:
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4